### ISSUE TITLE
Search facet configuration

### ISSUE THREAD

**Issue by fxprunayre** [eea/geonetwork-eea#5]
Add:
- Facet on group
- Facet on obsolete - 
  - see metadata MD_ProgressCode ongoing, conplete, ... 
  - display the info on the  recordView) 
  - add facet with or mode (like sextant)

**Comment by Delawen** [comment]
Right now this is already displayed on the record view. Should I add it to the results list?

![status_gn](https://cloud.githubusercontent.com/assets/726590/6124110/cfbc07c0-b10a-11e4-80e7-d984b354d53d.png)

**Comment by Delawen** [comment]
I modified the FacetsDirective to allow mixing "or" and "and" facets. Not sure if you like it enough to pull to develop.

Also, still not sure what and where should I add to recordview.
