### ISSUE TITLE
Search form / Advanced

### ISSUE THREAD

**Issue by fxprunayre** [eea/geonetwork-eea#6]
Add all existing fields to the advanced form which are not present on the facets.

**Comment by fxprunayre** [comment]
We did not discussed that much in Bennekom - the advanced form. So I would say do this only for EEA and we'll see what to backport to GN.

**Comment by Delawen** [comment]
Ok, I was taking a look at http://www.eea.europa.eu/data-and-maps/find/global and I see the advanced options (better said: facets) are quite different from geoNetwork original advanced options. Which one should I implement?

**Comment by fxprunayre** [comment]
No you should look to the metadata catalog
http://sdi.eea.europa.eu/catalogue/srv/eng/search?hl=en&extent=-12,3,37,72
or simply use the srv/eng/search service locally

**Comment by Delawen** [comment]
Let me know if you like how it look like.

I think the only thing missing now is the hits per page, which probably should go on develop too....

**Comment by fxprunayre** [comment]
> I think the only thing missing now is the hits per page, which probably should go on develop too....

hits per page is in search results toolbar which is good enough I think.

Will test. Thanks
