### ISSUE TITLE
Map / Disable it

### ISSUE THREAD

**Issue by fxprunayre** [eea/geonetwork-eea#8]
Maybe we should add a config option in GeoNetwork 3 to turn on/off the big map in the search page.

**Comment by Delawen** [comment]
You we are talking about the preview map with the bounding box of the results, right?
![map](https://cloud.githubusercontent.com/assets/726590/6037794/9f9aa84c-ac57-11e4-85c7-1981bdbba42a.png)

Even if this is on EEA repo, I should do this changes on geonetwork trunk, right?

**Comment by fxprunayre** [comment]
> You we are talking about the preview map with the bounding box of the results, right?

No some user does not want the bigmap viewer (and keep the minimap).

So having a config option to turn it on/off would be good.

I see 2 ways of doing it:
* use a CSS class which hide all bigmap related items: the mapviewer tab, the addtomap action
* or use a JS settings and use data-ng-show="isMapViewerEnabled" or something like this

Not sure which is best ?

The option could be added to the map config in the admin > settings for easier configuration.

Yep I think this should go in GN develop (GéoSource also turn the map off)

**Comment by Delawen** [comment]
Note to myself: This will also affect the actions related to the map (like add layer).

**Comment by Delawen** [comment]
https://github.com/geonetwork/core-geonetwork/commit/97bd61581ca3e190dffbc096c83f35a33e892d99
